# ExternalSecret: Customer Service 데이터베이스 자격 증명
# AWS Secrets Manager에서 시크릿을 가져와 Kubernetes Secret으로 생성
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: customer-service-db-secret
  namespace: ecommerce
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: customer-service-db-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: c4ang/customer-service/database
        property: username
    - secretKey: password
      remoteRef:
        key: c4ang/customer-service/database
        property: password

