# ServiceAccount: External Secrets Operator용 (IRSA)
# 실제 배포 시 ACCOUNT_ID와 ROLE_NAME을 변경해야 함
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: external-secrets-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/external-secrets-operator-role

